#!/bin/bash

# Stop on errors
set -e

echo ARCHITECTURE: `dpkg --print-architecture`

if [[ `dpkg --print-architecture` == "armhf" ]]; then
    PACKAGES=(
        libatlas3-base  # numpy piwheels
        libgfortran5  # numpy piwheels
        libxslt1.1  # lxml piwheels
        libicu63  # lxml piwheels
    )
else
    PACKAGES=(
    )
fi

# Required debian packages for building dependencies
PACKAGES_DEV=(
)

apt-get update -yy
apt-get install -yy --no-install-recommends ${PACKAGES[@]} ${PACKAGES_DEV[@]}

# Remove packages
apt-get remove -y --purge ${PACKAGES_DEV[@]}
apt-get -y --purge autoremove

# Cleanup
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/src/app/build/

# Update pip and poetry to latest
pip3 install --upgrade --no-cache-dir \
    --extra-index-url https://www.piwheels.hostedpi.com/simple \
    pip \
    poetry
