#!/bin/bash

# Stop on errors
set -e

if [[ `dpkg --print-architecture` == "*arm*" ]]; then
    PACKAGES=(
        # gcc  # compile python c-source
        # build-essential  # crypt
        libatlas3-base  # numpy piwheels
        libgfortran5  # numpy piwheels
        # libssl-dev  # crypt
        # libffi-dev  # crypt
        # python3-dev  # crypt
    )
else
    PACKAGES=(
    )
fi

# Required debian packages for building dependencies
PACKAGES_DEV=(
)

apt-get update -yy
apt-get install -yy --no-install-recommends ${PACKAGES[@]} ${PACKAGES_DEV[@]}

# Remove packages
apt-get remove -y --purge ${PACKAGES_DEV[@]}
apt-get -y --purge autoremove

# Cleanup
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/src/app/build/

# Update pip to latest
pip3 install --upgrade --no-cache-dir \
    pip \
    poetry
